# Generated by Django 4.2.7 on 2023-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_item_watchlist_notification_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='created_on',
            field=models.CharField(default='18/12/2023 14:55:08', max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.CharField(default='18/12/2023 14:55:08', max_length=64),
        ),
    ]
